; Supervisor config for Laravel photos queue worker
; Copy to: /etc/supervisor/conf.d/parser-worker-photos.conf

[program:parser-worker-photos]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/online-parser.siteaacess.store/artisan queue:work redis --queue=photos --sleep=3 --tries=5 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=2
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/online-parser.siteaacess.store/storage/logs/worker-photos.log
stopwaitsecs=3600
