# cheepy.shop — основной сайт (SPA)
server {
    server_name cheepy.shop www.cheepy.shop;
    root /var/www/siteaacess.store/dist;
    index index.html;

    location = /index.html {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }
    location / {
        try_files $uri $uri/ /index.html;
    }
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    listen [::]:443 ssl;
    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/cheepy.shop/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/cheepy.shop/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    listen 80;
    listen [::]:80;
    server_name cheepy.shop www.cheepy.shop;
    return 301 https://cheepy.shop$request_uri;
}
